# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    tags:
    - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Flutter action
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'
          cache: true

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - run: flutter pub get
      - run: flutter build linux --release

      - run: |
          pwd
          ls -la
          cd ./build
          ls -la
          cd ./linux
          ls -la
          cd x64
          ls -la
          cd release
          mv bundle adb-manager
          tar -czf ./linux-x64.tar.gz ./adb-manager

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./build/linux/x64/release/linux-x64.tar.gz"
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Flutter action
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter build windows --release
