# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Linux

on:
  push:
    tags:
    - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Flutter action
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev

      - run: flutter doctor -v

      - run: flutter pub get
      - run: flutter build -v linux --release

      - run: |
          cd ./build/linux/x64/release
          mv bundle adb-manager
          tar -czf ./linux-x64.tar.gz ./adb-manager

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./build/linux/x64/release/linux-x64.tar.gz"
