# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Windows

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: stable
          cache: true
      - run: flutter doctor -v

      - name: Get flutter dependencies
        run: flutter pub get

      - name: Build
        run: flutter build -v windows --release

      - name: Copy VC redistributables to release directory
        run: |
          Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\msvcp140.dll') .
          Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\vcruntime140.dll') .
          Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\vcruntime140_1.dll') .
        working-directory: build\windows\x64\runner\Release

      - name: Package files
        run: compress-archive -Path * -DestinationPath windows-x86_64.zip
        working-directory: build\windows\x64\runner

      - name: Upload artifacts to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./build/windows/x64/runner/windows-x86_64.zip